[package]
name = "staking"
version = "0.1.0"
description = "simple staking contract"
edition = "2024_07"

[dependencies]
starknet.workspace = true
openzeppelin_token = "0.17.0"
token = { path = "../token" }

[dev-dependencies]
assert_macros = "2.8.2"
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.33.0" }
utility = { path = "../utility" }

[[target.starknet-contract]]
build-external-contracts = [ "token::zeppelin_token::ZeppelinToken" ]
sierra = true
casm = true

[scripts]
test = "snforge test"