[workspace]
name = "mse_cairo_tech_talk"
version = "0.1.0"
description = "Some simple smart contracts"
homepage = "https://github.com/jbaettig/mse_cairo_tech_talk"
cairo-version = "2.8.5"
edition = "2024_07"
members = [
  "packages/balance",
  "packages/geometry",
  "packages/staking",
  "packages/token",
  "packages/utility",
]

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[workspace.dependencies]
starknet = "2.8.2"

[tool]
fmt.workspace = true