[package]
name = "balance"
version = "0.1.0"
description = "simple balance contract"
edition = "2024_07"

[dependencies]
starknet.workspace = true

[dev-dependencies]
assert_macros = "2.8.2"
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.33.0" }
utility = { path = "../utility" }

[[target.starknet-contract]]
sierra = true
casm = true

[scripts]
test = "snforge test"